# Generated by Django 4.2.3 on 2023-07-29 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeopathy_name', models.CharField(max_length=200)),
                ('potency_30', models.CharField(max_length=3)),
                ('potency_200', models.CharField(max_length=3)),
                ('potency_1m', models.CharField(max_length=3)),
                ('potency_ml1', models.CharField(max_length=3)),
                ('quantity_of_30', models.IntegerField()),
                ('quantity_of_200', models.IntegerField()),
                ('quantity_of_1m', models.IntegerField()),
                ('quantity_of_ml', models.IntegerField()),
                ('description', models.TimeField(blank=True)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
