# Generated by Django 4.2.3 on 2023-07-29 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='quantity_of_ml',
            new_name='quantity_of_ml1',
        ),
    ]
