# Generated by Django 4.2.3 on 2023-07-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_rename_quantity_of_ml_listing_quantity_of_ml1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo_main',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='potency_1m',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='listing',
            name='potency_200',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='listing',
            name='potency_30',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='listing',
            name='potency_ml1',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='listing',
            name='quantity_of_1m',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='quantity_of_200',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='quantity_of_30',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='quantity_of_ml1',
            field=models.IntegerField(blank=True),
        ),
    ]
