# Generated by Django 4.2.3 on 2023-07-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_photo_main_alter_listing_potency_1m_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo_main',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='potency_1m',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='listing',
            name='potency_200',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='listing',
            name='potency_30',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='listing',
            name='potency_ml1',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='listing',
            name='quantity_of_1m',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='quantity_of_200',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='quantity_of_30',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='quantity_of_ml1',
            field=models.IntegerField(),
        ),
    ]
