# Generated by Django 4.2.3 on 2023-07-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listing_photo_main_alter_listing_potency_1m_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
