# Generated by Django 4.2.3 on 2023-07-29 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_listing_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_main',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='potency_1m',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='potency_200',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='potency_30',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='potency_ml1',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='quantity_of_1m',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='quantity_of_200',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='quantity_of_30',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='quantity_of_ml1',
            field=models.IntegerField(null=True),
        ),
    ]
