# Generated by Django 4.2.3 on 2023-07-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_listing_list_date_alter_listing_photo_main_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='potency_1m',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='potency_200',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='potency_30',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='potency_ml1',
            field=models.BooleanField(null=True),
        ),
    ]
