# Generated by Django 4.2.3 on 2023-07-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_listing_potency_1m_alter_listing_potency_200_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TimeField(blank=True, max_length=1000, null=True),
        ),
    ]
